#pragma once

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <malloc.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <time.h>
#include <sys/stat.h>

typedef uint8_t uint8;



typedef unsigned char zBYTE;
typedef int16_t zSHORT;
typedef int16_t zSWORD;
typedef uint16_t zUINT16;
typedef uint16_t zWORD;
typedef int32_t zINT;
typedef int32_t zLONG;
typedef int32_t zBOOL;
typedef int32_t zFLAGS;
typedef uint32_t zUINT;
typedef uint32_t zDWORD;
typedef uint32_t zUINT32;
typedef size_t zSIZE_T;
typedef float zREAL;
typedef float zVALUE;

#define zREAL_MAX ((zREAL)+FLT_MAX)
#define zREAL_MIN ((zREAL)-FLT_MAX)

#ifndef _WIN32
#define stricmp strcasecmp
#endif

#define FALSE 0
#define TRUE 1

#define zOK 0
#define zERROR 1

#define TEXTURE_FILE_VERSION_GOTHIC_1_01 ((zWORD)0x0000)
#define TEXTURE_FILE_VERSION_GOTHIC_1_04 TEXTURE_FILE_VERSION_GOTHIC_1_01
#define TEXTURE_FILE_VERSION_GOTHIC_1_30 ((zWORD)0x0001)

#define MESH_FILE_VERSION_GOTHIC_1_01 ((zWORD)0x0009)
#define MESH_FILE_VERSION_GOTHIC_1_04 MESH_FILE_VERSION_GOTHIC_1_01
#define MESH_FILE_VERSION_GOTHIC_1_30 MESH_FILE_VERSION_GOTHIC_1_04

#define MESH_VERSION_GOTHIC_1_01 (zWORD((TEXTURE_FILE_VERSION_GOTHIC_1_01 << 8) + MESH_FILE_VERSION_GOTHIC_1_01))
#define MESH_VERSION_GOTHIC_1_04 MESH_VERSION_GOTHIC_1_01
#define MESH_VERSION_GOTHIC_1_30 (zWORD((TEXTURE_FILE_VERSION_GOTHIC_1_30 << 8) + MESH_FILE_VERSION_GOTHIC_1_30))

#define BSP_VERSION_GOTHIC_1_01 ((zWORD)0x0001)
#define BSP_VERSION_GOTHIC_1_04 ((zWORD)0x0002)
#define BSP_VERSION_GOTHIC_1_30 ((zWORD)0x0003)

#define BSPMESH_VERSION_GOTHIC_1_01 (zDWORD((MESH_VERSION_GOTHIC_1_01 << 16) + (BSP_VERSION_GOTHIC_1_01 << 24)))
#define BSPMESH_VERSION_GOTHIC_1_04 (zDWORD((MESH_VERSION_GOTHIC_1_04 << 16) + (BSP_VERSION_GOTHIC_1_04 << 24)))
#define BSPMESH_VERSION_GOTHIC_1_30 (zDWORD((MESH_VERSION_GOTHIC_1_30 << 16) + (BSP_VERSION_GOTHIC_1_30 << 24)))

#define MATERIAL_VERSION_SUM_GOTHIC_1_01 ((zWORD)0x4400)
#define MATERIAL_VERSION_SUM_GOTHIC_1_04 MATERIAL_VERSION_SUM_GOTHIC_1_01
#define MATERIAL_VERSION_SUM_GOTHIC_OLD1 ((zWORD)0x7401)
#define MATERIAL_VERSION_SUM_GOTHIC_OLD2 ((zWORD)0x6002)
#define MATERIAL_VERSION_SUM_GOTHIC_1_30 ((zWORD)0x9C03)

#define MATERIAL_FILE_VERSION_GOTHIC_1_01 ((zWORD)0x0003)
#define MATERIAL_FILE_VERSION_GOTHIC_1_04 MATERIAL_FILE_VERSION_GOTHIC_1_01
#define MATERIAL_FILE_VERSION_GOTHIC_OLD1 ((zWORD)0x0007)
#define MATERIAL_FILE_VERSION_GOTHIC_OLD2 ((zWORD)0x0008)
#define MATERIAL_FILE_VERSION_GOTHIC_1_30 ((zWORD)0x0009)

#define MORPHMESH_VERSION_GOTHIC_1_01 ((zDWORD)0x00000003)
#define MORPHMESH_VERSION_GOTHIC_1_04 MORPHMESH_VERSION_GOTHIC_1_01
#define MORPHMESH_VERSION_GOTHIC_1_30 MORPHMESH_VERSION_GOTHIC_1_04

#define PROGMESH_FILE_VERSION_GOTHIC_1_01 ((zWORD)0x0005)
#define PROGMESH_FILE_VERSION_GOTHIC_1_04 PROGMESH_FILE_VERSION_GOTHIC_1_01
#define PROGMESH_FILE_VERSION_GOTHIC_1_30 PROGMESH_FILE_VERSION_GOTHIC_1_04

#define PROGMESH_VERSION_GOTHIC_1_01 ((zWORD)((MATERIAL_FILE_VERSION_GOTHIC_1_01 << 8) + PROGMESH_FILE_VERSION_GOTHIC_1_01))
#define PROGMESH_VERSION_GOTHIC_1_04 ((zWORD)((MATERIAL_FILE_VERSION_GOTHIC_1_04 << 8) + PROGMESH_FILE_VERSION_GOTHIC_1_04))
#define PROGMESH_VERSION_GOTHIC_OLD1 ((zWORD)((MATERIAL_FILE_VERSION_GOTHIC_OLD1 << 8) + PROGMESH_FILE_VERSION_GOTHIC_1_30))
#define PROGMESH_VERSION_GOTHIC_OLD2 ((zWORD)((MATERIAL_FILE_VERSION_GOTHIC_OLD2 << 8) + PROGMESH_FILE_VERSION_GOTHIC_1_30))
#define PROGMESH_VERSION_GOTHIC_1_30 ((zWORD)((MATERIAL_FILE_VERSION_GOTHIC_1_30 << 8) + PROGMESH_FILE_VERSION_GOTHIC_1_30))

#define MESHSOFTSKIN_FILE_VERSION_GOTHIC_1_01 ((zDWORD)0x00000004)
#define MESHSOFTSKIN_FILE_VERSION_GOTHIC_1_04 MESHSOFTSKIN_FILE_VERSION_GOTHIC_1_01
#define MESHSOFTSKIN_FILE_VERSION_GOTHIC_1_30 MESHSOFTSKIN_FILE_VERSION_GOTHIC_1_04

#define MODELHIERARCHY_VERSION_GOTHIC_1_01 (zDWORD(0x00000003))
#define MODELHIERARCHY_VERSION_GOTHIC_1_04 MODELHIERARCHY_VERSION_GOTHIC_1_01
#define MODELHIERARCHY_VERSION_GOTHIC_1_30 MODELHIERARCHY_VERSION_GOTHIC_1_04

#define MAN_FILE_VERSION_GOTHIC_1_01 ((zWORD)0x000C)
#define MAN_FILE_VERSION_GOTHIC_1_04 MAN_FILE_VERSION_GOTHIC_1_01
#define MAN_FILE_VERSION_GOTHIC_1_30 MAN_FILE_VERSION_GOTHIC_1_04

#define MODELMESH_FILE_VERSION_GOTHIC_1_01 ((zDWORD)0x00000006)
#define MODELMESH_FILE_VERSION_GOTHIC_1_04 MODELMESH_FILE_VERSION_GOTHIC_1_01
#define MODELMESH_FILE_VERSION_GOTHIC_1_30 MODELMESH_FILE_VERSION_GOTHIC_1_04

#define MODELMESH_VERSION_GOTHIC_1_01 ((zDWORD)(MODELMESH_FILE_VERSION_GOTHIC_1_01 + (((zDWORD)PROGMESH_VERSION_GOTHIC_1_01) << 8) + (MESHSOFTSKIN_FILE_VERSION_GOTHIC_1_01 << 24)))
#define MODELMESH_VERSION_GOTHIC_1_04 ((zDWORD)(MODELMESH_FILE_VERSION_GOTHIC_1_04 + (((zDWORD)PROGMESH_VERSION_GOTHIC_1_04) << 8) + (MESHSOFTSKIN_FILE_VERSION_GOTHIC_1_04 << 24)))
#define MODELMESH_VERSION_GOTHIC_OLD1 ((zDWORD)(MODELMESH_FILE_VERSION_GOTHIC_1_30 + (((zDWORD)PROGMESH_VERSION_GOTHIC_OLD1) << 8) + (MESHSOFTSKIN_FILE_VERSION_GOTHIC_1_30 << 24)))
#define MODELMESH_VERSION_GOTHIC_OLD2 ((zDWORD)(MODELMESH_FILE_VERSION_GOTHIC_1_30 + (((zDWORD)PROGMESH_VERSION_GOTHIC_OLD2) << 8) + (MESHSOFTSKIN_FILE_VERSION_GOTHIC_1_30 << 24)))
#define MODELMESH_VERSION_GOTHIC_1_30 ((zDWORD)(MODELMESH_FILE_VERSION_GOTHIC_1_30 + (((zDWORD)PROGMESH_VERSION_GOTHIC_1_30) << 8) + (MESHSOFTSKIN_FILE_VERSION_GOTHIC_1_30 << 24)))

#define MSB_FILE_VERSION_GOTHIC_1_30 ((zDWORD)0x00000001)

#include "Memory.h"
#include "String.h"
#include "Container.h"
#include "Disk.h"
#include "ScanDir.h"
#include "Algebra.h"
#include "Color.h"
#include "Material.h"
#include "3D.h"
#include "Mesh.h"
#include "Bsp.h"
#include "World.h"
#include "ProgMesh.h"
#include "MorphMesh.h"
#include "Model.h"
#include "ModelAni.h"

extern zDWORD meshAndBspVersionIn;
extern zWORD meshVersionIn;
extern zWORD bspVersionIn;
extern zWORD materialVersionIn;

extern zDWORD morphMeshVersionIn;
extern zWORD progMeshVersionIn;
extern zDWORD meshSoftSkinVersionIn;
extern zDWORD modelHierarchyVersionIn;
extern zDWORD modelMeshVersionIn;
extern zWORD modelAnimationVersionIn;
extern zDWORD modelScriptVersionIn;

extern zDWORD meshAndBspVersionOut;
extern zWORD meshVersionOut;
extern zWORD bspVersionOut;
extern zWORD materialVersionOut;

extern zDWORD morphMeshVersionOut;
extern zWORD progMeshVersionOut;
extern zDWORD meshSoftSkinVersionOut;
extern zDWORD modelHierarchyVersionOut;
extern zDWORD modelMeshVersionOut;
extern zWORD modelAnimationVersionOut;
extern zDWORD modelScriptVersionOut;

extern zBOOL xZenIn;
extern zBOOL xZenOut;

extern zBOOL deCompile;
extern zBOOL deLod;
